language: go

go:
- "1.10.x"
- master

install:
- go get github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/cover

script:
- go test -v -race ./.
- goveralls -service=travis-ci

notifications:
  email: false